<a href="https://colab.research.google.com/github/anjaliasha123/AirlineTweetClassification/blob/main/src/BiLSTMCNNAtt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


Initial required libraries

In [2]:
import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#intializing global variables
data = pd.read_csv('https://raw.githubusercontent.com/anjaliasha123/Data_Visualization_projects/master/Streamlit_python/Tweets.csv')
Xdata = data[['airline_sentiment_confidence','airline','text','latitude','longitude']]
Ydata = data['airline_sentiment']

In [4]:
Xdata.head(10)

airline_sentiment_confidence         airline  ...   latitude   longitude
0                        1.0000  Virgin America  ...  35.888455 -119.273781
1                        0.3486  Virgin America  ...  37.770971 -119.941025
2                        0.6837  Virgin America  ...  35.684863 -119.709299
3                        1.0000  Virgin America  ...  37.061159 -119.279135
4                        1.0000  Virgin America  ...  36.790587 -120.867752
5                        1.0000  Virgin America  ...  36.226653 -119.290923
6                        0.6745  Virgin America  ...  33.778164 -119.565305
7                        0.6340  Virgin America  ...  36.485239 -119.301841
8                        0.6559  Virgin America  ...  36.208968 -119.087950
9                        1.0000  Virgin America  ...  37.694475 -119.006906

[10 rows x 5 columns]

In [5]:
Ydata = Ydata.to_frame()
Ydata.head(2)

airline_sentiment
0           neutral
1          positive

In [6]:
most_common = 20000
max_len = 100
epochs = 10
embed_dim = 100
batch_size = 50

#Function to create word embeddings

- we use pre-trained glove model to create word2vec 
- create a embedding matrix

In [ ]:
from utilsfunction  import dataPreprocessing

In [8]:
em, X, y = dataPreprocessing(Xdata,Ydata, most_common=most_common, max_len= max_len, embed_dim=embed_dim)

Found 15768 unique tokens.


 Labels:  ['negative', 'positive', 'neutral']
airline_sentiment
negative             9178
neutral              3099
positive             2363
dtype: int64
  airline_sentiment  label
0           neutral      0
1          positive      1
[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
Text 1:  @VirginAmerica What @dhepburn said.
Text 1 converted to word index sequences:  [81, 62, 6686, 226]
Text 1 word to padded index sequence of length 100: 
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0   81   62
 6686  226]
